# A Simple Model

In [2]:
!pip install -r requirements.txt

Requirement already satisfied: scikit-learn in /home/codespace/.local/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (1.1.3)
Requirement already satisfied: pandas in /home/codespace/.local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (1.5.1)
Requirement already satisfied: matplotlib in /home/codespace/.local/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (3.6.0)
Requirement already satisfied: numpy in /home/codespace/.local/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (1.23.4)
Collecting sf-hamilton
  Downloading sf_hamilton-1.11.0-py3-none-any.whl (106 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.3/106.3 kB 2.6 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/codespace/.local/lib/python3.10/site-packages (from scikit-learn->-r requirements.txt (line 1)) (3.1.0)
Requirement already satisfied: scipy>=1.3.2 in /home/codespace/.local/lib/python3.10/site-packages (from scikit-learn->-r requirements.txt (line 1)) (1.9.3)
Requirement already satisfied: joblib>=1.0.0 in /home/codespace/.local/lib/python3.10/site-packages (from scikit-learn->-r requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: pytz>=2020.1 in /home/codespace/.local/lib/python3.10/site-packages (from pandas->-r requirements.txt (line 2)) (2022.6)
Requirement already satisfied: python-dateutil>=2.8.1 in /home/codespace/.local/lib/python3.10/site-packages (from pandas->-r requirements.txt (line 2)) (2.8.2)
Requirement already satisfied: fonttools>=4.22.0 in /home/codespace/.local/lib/python3.10/site-packages (from matplotlib->-r requirements.txt (line 3)) (4.38.0)
Requirement already satisfied: packaging>=20.0 in /home/codespace/.local/lib/python3.10/site-packages (from matplotlib->-r requirements.txt (line 3)) (21.3)
Requirement already satisfied: pillow>=6.2.0 in /home/codespace/.local/lib/python3.10/site-packages (from matplotlib->-r requirements.txt (line 3)) (9.3.0)
Requirement already satisfied: cycler>=0.10 in /home/codespace/.local/lib/python3.10/site-packages (from matplotlib->-r requirements.txt (line 3)) (0.11.0)
Requirement already satisfied: pyparsing>=2.2.1 in /home/codespace/.local/lib/python3.10/site-packages (from matplotlib->-r requirements.txt (line 3)) (3.0.9)
Requirement already satisfied: contourpy>=1.0.1 in /home/codespace/.local/lib/python3.10/site-packages (from matplotlib->-r requirements.txt (line 3)) (1.0.6)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/codespace/.local/lib/python3.10/site-packages (from matplotlib->-r requirements.txt (line 3)) (1.4.4)
Collecting typing-inspect
  Downloading typing_inspect-0.8.0-py3-none-any.whl (8.7 kB)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas->-r requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: typing-extensions>=3.7.4 in /home/codespace/.local/lib/python3.10/site-packages (from typing-inspect->sf-hamilton->-r requirements.txt (line 5)) (4.4.0)
Collecting mypy-extensions>=0.3.0
  Downloading mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Installing collected packages: mypy-extensions, typing-inspect, sf-hamilton
Successfully installed mypy-extensions-0.4.3 sf-hamilton-1.11.0 typing-inspect-0.8.0

[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: python -m pip install --upgrade pip

In [11]:
from hamilton import driver, base
import simple_model_features
import importlib
importlib.reload(simple_model_features)

In [8]:
# create the training set -- 
train_df_path = "playdata/train.csv"
index_col = 'passengerid'

config = {
    'location': train_df_path,
    'index_col': index_col
}

dr = driver.Driver(config, simple_model_features)
dr.execute(['final_imputed_features'])

,pclass,age,fare,cabin_category,sex_category,embarked_category,family
passengerid,,,,,,,
0,1,0.00,27.14,12811,1,2,2
1,3,0.00,13.35,26992,1,2,0
2,3,0.33,71.29,26992,1,2,3
3,3,19.00,13.04,26992,1,2,0
4,3,25.00,7.76,26992,1,2,0
...,...,...,...,...,...,...,...
99995,2,62.00,14.86,22061,0,0,0
99996,2,66.00,11.15,26992,1,2,0
99997,3,37.00,9.95,26992,1,2,0
99998,3,51.00,30.92,26992,1,2,1
99999,3,55.00,13.96,26992,1,2,0

In [13]:
# create the training set and the model
import model_pipeline
importlib.reload(model_pipeline)

train_df_path = "playdata/train.csv"
index_col = 'passengerid'

config = {
    'location': train_df_path,
    'index_col': index_col,
    'target_col': 'survived',
    'random_state': 42,
    'max_depth': None,
    'validation_size_fraction': 0.33,
}

adapter = base.SimplePythonGraphAdapter(base.DictResult())

dr = driver.Driver(config, simple_model_features, model_pipeline, adapter=adapter)
result = dr.execute(['train_predictions', 'test_predictions'])
print(result)

{'train_predictions': (array([0.02, 0.61, 0.01, ..., 0.96, 0.  , 0.  ]), array([0, 1, 0, ..., 1, 0, 0])), 'test_predictions': (array([0.01 , 0.72 , 0.27 , ..., 0.32 , 0.625, 0.66 ]), array([0, 1, 0, ..., 0, 1, 1]))}